#include<stdio.h>
int main(void)
{
    int i,j;
    printf("Enter first number : ");
    scanf("%d",&i);
    if(i>1)
    {
        if(i>2)
        {
            if(i>3)
            {
                if(i>4)
                {
                    if(i>5)
                    {
                        if(i>6)
                        {
                            if(i>7)
                            {
                                if(i>8)
                                {
                                    if(i>9)
                                    {
                                        if(i>10)
                                        {
                                            if(i>11)
                                            {
                                                if(i>12)
                                                {
                                                    if(i>13)
                                                    {
                                                        if(i>14)
                                                        {
                                                            if(i>15)
                                                            {
                                                                if(i>16)
                                                                {
                                                                    if(i>17)
                                                                    {
                                                                        if(i>18)
                                                                        {
                                                                            if(i>19)
                                                                            {
                                                                                if(i>20)
                                                                                {
                                                                                    if(i>21)
                                                                                    {
                                                                                        if(i>22)
                                                                                        {
                                                                                            if(i>23)
                                                                                            {
                                                                                                if(i>24)
                                                                                                {
                                                                                                    if(i>25)
                                                                                                    {
                                                                                                        if(i>26)
                                                                                                        {
                                                                                                            if(i>27)
                                                                                                            {
                                                                                                                if(i>28)
                                                                                                                {
                                                                                                                    if(i>29)
                                                                                                                    {
                                                                                                                        if(i>30)
                                                                                                                        {
                                                                                                                            if(i>31)
                                                                                                                            {
                                                                                                                                if(i>32)
                                                                                                                                {
                                                                                                                                    if(i>33)
                                                                                                                                    {
                                                                                                                                        printf("Yes");
                                                                                                                                    }
                                                                                                                                }
                                                                                                                            }
                                                                                                                        }
                                                                                                                    }
                                                                                                                }
                                                                                                            }
                                                                                                        }
                                                                                                    }
                                                                                                }
                                                                                            }
                                                                                        }
                                                                                    }
                                                                                }
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
    //printf("Yes");

    return 0;
}
